// common layout state
export const TOGGLE_SIDEBAR = "toggle";
export const TOGGLE_FULL_BOT_INVENTORY = "TOGGLE_FULL_BOT_INVENTORY";

// auth
export const LOGGED = "LOGGED";
export const LOGOUT = "LOGOUT";

// profile state
export const GET_PROFILE_REQUEST = "GET_PROFILE_REQUEST";
export const GET_PROFILE_SUCCESS = "GET_PROFILE_SUCCESS";
export const GET_PROFILE_ERROR = "GET_PROFILE_ERROR";

export const GET_PROFILE_HISTORY_REQUEST = "GET_PROFILE_HISTORY_REQUEST";
export const GET_PROFILE_HISTORY_SUCCESS = "GET_PROFILE_HISTORY_SUCCESS";
export const GET_PROFILE_HISTORY_ERROR = "GET_PROFILE_HISTORY_ERROR";

export const GET_PROFILE_MULTI_REQUEST = "GET_PROFILE_MULTI_REQUEST";
export const GET_PROFILE_MULTI_SUCCESS = "GET_PROFILE_MULTI_SUCCESS";
export const GET_PROFILE_MULTI_ERROR = "GET_PROFILE_MULTI_ERROR";

export const DELETE_PROFILE_MULTI_REQUEST = "DELETE_PROFILE_MULTI_REQUEST";
export const DELETE_PROFILE_MULTI_SUCCESS = "DELETE_PROFILE_MULTI_SUCCESS";
export const DELETE_PROFILE_MULTI_ERROR = "DELETE_PROFILE_MULTI_ERROR";

export const SET_PROFILE_TRADELINK = "set-profile-tradelink";
export const SET_PROFILE_STATISTIC = "set-profile-statistic";
export const SET_PROFILE_INFO = "set-profile-info";

// deals
export const GET_DEALS_CHANGE_QUEUE_SIZE = "GET_DEALS_CHANGE_QUEUE_SIZE";
export const GET_DEALS_ADD = "GET_DEALS_ADD";
export const GET_DEALS_ERROR = "GET_DEALS_ERROR";

// sell bot
export const AGREE_TERMS_SELL_BOT = "AGREE_TERMS_SELL_BOT";
export const SELL_BOT_STEAM_LINK = "SELL_BOT_STEAM_LINK";

export const GET_INVENTORY = "GET_INVENTORY";
export const GET_INVENTORY_SUCCESS = "GET_INVENTORY_SUCCESS";
export const GET_INVENTORY_ERROR = "GET_INVENTORY_ERROR";
export const SET_INVENTORY_FILTER = "SET_INVENTORY_FILTER";
export const CLEAR_INVENTORY = "CLEAR_INVENTORY";

export const SET_LOGGER_DATA = "SET_LOGGER_DATA";
export const RESET_LOGGER = "RESET_LOGGER";
export const CHANGE_LOGGER_STATE = "CHANGE_LOGGER_STATE";
export const DELETE_MAFILE = "DELETE_MAFILE";
export const SET_LOGGER_MODE = "SET_LOGGER_MODE";
export const SET_LOGGER_INFO_VALIDATION_STATE =
  "SET_LOGGER_INFO_VALIDATION_STATE";

export const SHOW_ITEMS_SHADOW = "SHOW_ITEMS_SHADOW";
export const DISPLAY_NONE = "DISPLAY_NONE";

// currency
export const ADD_CURRENCIES = "ADD_CURRENCIES";
export const SET_CURRENCY = "SET_CURRENCY";
export const SET_CURRENCY_LOADED = "SET_CURRENCY_LOADED";

// payment
export const SET_TAB_PAYMENT = "SET_TAB_PAYMENT";
export const SET_CURRENT_PAYMENT = "SET_CURRENT_PAYMENT";
export const SET_VALIDATION_ERROR = "SET_VALIDATION_ERROR";
export const SET_PAYMENT_TRANSACTION = "SET_PAYMENT_TRANSACTION";
export const SET_DISABLED_STATE = "SET_DISABLED_STATE";
export const SET_NEW_TRANSACTION = "SET_NEW_TRANSACTION";
export const SET_VALIDATION_STATE = "SET_VALIDATION_STATE";
export const SET_LOADER = "SET_LOADER";
export const CLEAR_TRANSACTIONS = "CLEAR_TRANSACTIONS";
export const SET_REQUEST_RESULT = "SET_REQUEST_RESULT";
export const SET_CURRENT_TRANSACTION = "SET_CURRENT_TRANSACTION";
