// common layout state
export const TOGGLE_SIDEBAR = "toggle";
export const TOGGLE_FULL_BOT_INVENTORY = "TOGGLE_FULL_BOT_INVENTORY";

// auth
export const LOGOUT = "LOGOUT";
export const LOGIN = "LOGIN";

// profile state
export const GET_PROFILE_REQUEST = "GET_PROFILE_REQUEST";
export const GET_PROFILE_SUCCESS = "GET_PROFILE_SUCCESS";
export const GET_PROFILE_ERROR = "GET_PROFILE_ERROR";

export const GET_PROFILE_HISTORY_REQUEST = "GET_PROFILE_HISTORY_REQUEST";
export const GET_PROFILE_HISTORY_SUCCESS = "GET_PROFILE_HISTORY_SUCCESS";
export const GET_PROFILE_HISTORY_ERROR = "GET_PROFILE_HISTORY_ERROR";

export const GET_PROFILE_MULTI_REQUEST = "GET_PROFILE_MULTI_REQUEST";
export const GET_PROFILE_MULTI_SUCCESS = "GET_PROFILE_MULTI_SUCCESS";
export const GET_PROFILE_MULTI_ERROR = "GET_PROFILE_MULTI_ERROR";

export const DELETE_PROFILE_MULTI_REQUEST = "DELETE_PROFILE_MULTI_REQUEST";
export const DELETE_PROFILE_MULTI_SUCCESS = "DELETE_PROFILE_MULTI_SUCCESS";
export const DELETE_PROFILE_MULTI_ERROR = "DELETE_PROFILE_MULTI_ERROR";

export const SET_PROFILE_TRADELINK = "set-profile-tradelink";
export const SET_PROFILE_STATISTIC = "set-profile-statistic";
export const SET_PROFILE_INFO = "set-profile-info";

// deals
export const GET_DEALS_CHANGE_QUEUE_SIZE = "GET_DEALS_CHANGE_QUEUE_SIZE";
export const GET_DEALS_ADD = "GET_DEALS_ADD";
export const GET_DEALS_ERROR = "GET_DEALS_ERROR";

// item prices
export const GET_ITEM_PRICES = "GET_ITEM_PRICES";
export const GET_ITEM_PRICES_SUCCESS = "GET_ITEM_PRICES_SUCCESS";
export const GET_ITEM_PRICES_ERROR = "GET_ITEM_PRICES_ERROR";

export const GET_INVENTORY = "GET_INVENTORY";
export const GET_INVENTORY_SUCCESS = "GET_INVENTORY_SUCCESS";
export const GET_INVENTORY_ERROR = "GET_INVENTORY_ERROR";

// currency
export const ADD_CURRENCIES = "ADD_CURRENCIES";
export const SET_CURRENCY = "SET_CURRENCY";
export const SET_CURRENCY_LOADED = "SET_CURRENCY_LOADED";

// payment
export const SET_TAB_PAYMENT = "SET_TAB_PAYMENT";
export const SET_CURRENT_PAYMENT = "SET_CURRENT_PAYMENT";
export const SET_VALIDATION_ERROR = "SET_VALIDATION_ERROR";
export const SET_PAYMENT_TRANSACTION = "SET_PAYMENT_TRANSACTION";
export const SET_DISABLED_STATE = "SET_DISABLED_STATE";
export const SET_NEW_TRANSACTION = "SET_NEW_TRANSACTION";
